services:
  tournament-api-service:
    build:
      context: .
      dockerfile: ApiService/Dockerfile
    container_name: tournament-api-service
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tournament_service
      DB_USERNAME: postgres
      DB_PASSWORD: root
    ports:
      - "8080:8081"
    networks:
      - tournament-network

  db:
    image: postgres:18
    container_name: tournament-postgres
    restart: unless-stopped
    environment:
      url: jdbc:postgresql://localhost:5432/tournament_service
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    networks:
      - tournament-network

networks:
  tournament-network:
    driver: bridge